// <auto-generated />
using System;
using BLOG_API_01.WebDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BLOG_API_01.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260409055754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BLOG_API_01.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BlogCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 5, 57, 54, 298, DateTimeKind.Utc).AddTicks(5265),
                            BlogTitle = "Nghị luận xã hội 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 5, 57, 54, 298, DateTimeKind.Utc).AddTicks(5268),
                            BlogTitle = "Nghị luận xã hội 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 5, 57, 54, 298, DateTimeKind.Utc).AddTicks(5271),
                            BlogTitle = "Nghị luận xã hội 3",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BLOG_API_01.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "HA@gmail.com",
                            Name = "HA",
                            Password = "wWX71uyG0FBhhrJYi3DvoticP3X1EyVjXlVanzVH9bruG/l1gahbOG1kouLbhDJ7HLQq72NZIOtZn8tHGQUDSfRtAEm/BMlm5rE9NUP/TWnWbIBKhM0AOkTB2et2jw6tFOmiZOf8Dd1GnYLQP7NEqqqXeVrJ6FCb9BYAxIi4/8o=.eFAT5NHpAVIOFx2V4UxHOPU5iA5s67Fqloamp8PGmPiDVcMKjRe/BeWOL7KyCNYOn9UFPyG/S1kPhGeREsXcog==",
                            Role = "admin",
                            UserName = "kenshin4125"
                        },
                        new
                        {
                            Id = 2,
                            Email = "TQ@gmail.com",
                            Name = "TQ",
                            Password = "cENlO0nEtBxskcA5y12SeLgmfR2Ap5ZWSwDD1iYevSZpHFfFF5Ykj2xWh5eq0HYttlCC8cHwVEb4E9OuBAEvV0F2qRlOnPcJf5G5VNDOkd/7uumxS5lTnXkDWXZuyUwyZ77x8L0cnlB3XDGYTOSqd9R9esInwXMm4CP6gOYv2AU=.98C08JQdxgBufmra/bjYVIljiS1H8NWj8zta9uAyNlCpZMQbO0qr0iBTF8ORUbkNU0F+MtjZVnR5gB4+HAwRwg==",
                            Role = "user",
                            UserName = "cuteyb"
                        },
                        new
                        {
                            Id = 3,
                            Email = "he@gmail.com",
                            Name = "hehe1",
                            Password = "Uh7KJzez2JdpkgZhtpR+wdhXj/ij4VgrS29P1CQf5n85h5EehlM/i9cY6PjNBNAfmGDdxCYS/qReUtbKaLG+2YlLw2cVOqMTWD1RarHl7xRoslCgu/y8+pnXZQSsvpkyF+0Zyiks3A4FJ1SnV/QnPZuG7j5EuPJZYyuaDCKj0v4=.K1/xQx8dIZdgmdyBQ9jT6bWhRyRs7RXJDE8whKvLGBDmZech8KXsKcWL37M0Zpoa+Oml8ubQ4+JTrSYA3UEpbg==",
                            Role = "user",
                            UserName = "hehe"
                        });
                });

            modelBuilder.Entity("BLOG_API_01.Models.Blog", b =>
                {
                    b.HasOne("BLOG_API_01.Models.User", null)
                        .WithMany("blogId")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLOG_API_01.Models.User", b =>
                {
                    b.Navigation("blogId");
                });
#pragma warning restore 612, 618
        }
    }
}
