// <auto-generated />
using System;
using BLOG_API_01.WebDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BLOG_API_01.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260409122750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BLOG_API_01.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BlogCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 12, 27, 50, 170, DateTimeKind.Utc).AddTicks(6534),
                            BlogTitle = "Nghị luận xã hội 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 12, 27, 50, 170, DateTimeKind.Utc).AddTicks(6537),
                            BlogTitle = "Nghị luận xã hội 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BlogContent = "qwefuhudvuohwuefquowegfyqwbefhshdhbdkvawe",
                            BlogCreateTime = new DateTime(2026, 4, 9, 12, 27, 50, 170, DateTimeKind.Utc).AddTicks(6538),
                            BlogTitle = "Nghị luận xã hội 3",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BLOG_API_01.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "HA@gmail.com",
                            Name = "HA",
                            Password = "8LOW4OrE3h0wlXm1P9ewPEwXO3PtaJrHdqjLEVSzi86YWMLsU9LM+YHOQSrBIXS4yT5rJa4WdnGRPNfTMMP0+hnk3zwOPkgHJDf8IrlUiFXNo+oYkWBi84jEVCNQyAdZionJZUljE7yDg22luIiznWSgnHciUt0kb+/89ObWhBo=.FemWYCzSGQxTlyEU9Ow6XqQhv7DxlIm8kX7kil33sUHdo74VatWGMbSqLXminFtr3b8S93ilD7Fo6zypUcIECw==",
                            Role = "admin",
                            UserName = "kenshin4125"
                        },
                        new
                        {
                            Id = 2,
                            Email = "TQ@gmail.com",
                            Name = "TQ",
                            Password = "lb2737W9dE5LNuZrugTsXWgyzwUzla55DkAu6A/CFK37gDeOWMHu4vCWQdPfQ8AzMzKJr5TDKJto/hVFStlRbgYhmcn5il55lZV1X8m/iqXjmt+NkkTyYdWQI3wuPT2JASTrv49bLJ5XrZ9yj4GdFWB4JkK/W6/eoPmLFBlbhiE=.sBG0ljosNDKWD9A+LvUE8neRTB2XC4z1eGHCPt2o3l8uybivqFsw0wcvLBlTQEcMLzYocpLyLpmceOkvoRuSLA==",
                            Role = "user",
                            UserName = "cuteyb"
                        },
                        new
                        {
                            Id = 3,
                            Email = "he@gmail.com",
                            Name = "hehe1",
                            Password = "ng61X4d8J/mNag2fkDjuOLFI9voWLvRcxhVgIO0a31HkCeePhFPPCcImkz/WbMG55WI+hNGz/QUgyRhejSCY5AR8TLsIqOPwSW9ImDAw+IZZS4bNRCZ/tFLGcrtTZGepU4dU5OZgWXBNQjS2+HOxm8GPsRg2yheWRtjAlT93L80=.h4+JZdoASMhWhMs++nRFI9ysTL80vAgrvDT57WvuTTbtomSNAfetEWcIaibvNp3gBlLckPaHlt2c5uQxMJpeRw==",
                            Role = "user",
                            UserName = "hehe"
                        });
                });

            modelBuilder.Entity("BLOG_API_01.Models.Blog", b =>
                {
                    b.HasOne("BLOG_API_01.Models.User", null)
                        .WithMany("blogId")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLOG_API_01.Models.User", b =>
                {
                    b.Navigation("blogId");
                });
#pragma warning restore 612, 618
        }
    }
}
